version: "3.8"

x-php-service: &php-service
  image: php:8.3-cli
  volumes:
    - .:/app
  working_dir: /app
  tty: true

services:
  web:
    image: php:8.3-cli
    volumes:
      - .:/app
    working_dir: /app/src
    ports:
      - "8000:8000"
    command: php -S 0.0.0.0:8000
